version: 1
policy:
  pullRequests: collaborators
tasks:
  $match:
    'tasks_for == "github-push" && event.ref == "refs/heads/testing"':
      taskId: {$eval: as_slugid("testing_task")}
      created: {$fromNow: ''}
      deadline: {$fromNow: '1 hour'}
      provisionerId: 'aws-provisioner-v1'
      workerType: 'github-worker'
      scopes:
        - secrets:get:repo:github.com/mozilla-releng/product-details:branch:testing
      payload:
        maxRunTime: 3600
        image: python
        command:
          - /bin/bash
          - '--login'
          - '-c'
          - >-
            git clone ${event.repository.clone_url} repo && cd repo && 
            git checkout ${event.after}
      metadata:
        name: deploy testing
        description: 'Deploy to https://product-details.testing.mozilla-releng.net/'
        owner: ${event.pusher.name}@users.noreply.github.com
        source: ${event.repository.url}
